# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery'),
            preserve_default=False,
        ),
    ]
